### ISSUE TITLE
Why WEBPA protocol is more efficient than TR-69 or SNMP？

### ISSUE THREAD

**Issue by HapuHXY** [xmidt-org/parodus#355]
Hey, the idea behind Parodus is very inspiring. However, I still feel confused in some ways. Could you explain it further why "WEBPA protocol provides functionality of read/write access to device management parameters in an efficient manner as compared to TR-69 or SNMP" ? Thanks!

**Comment by schmidtw** [comment]
Largely it has to do with a few design choices.  Webpa & Xmidt.  Xmidt is really where the improvements are.  Webpa is "simply a translation layer" that provides a friendly RESTful way to get to the TR-181 or similar object.  Xmidt is the infrastructure that handles the message routing aspects, the websocket and similar things.

Now to get to some of the details you are interested in.

1. Xmidt has an always on websocket between parodus (client) and talaria (cloud).  There is no time lost waiting for a reconnection attempt, trying to tunnel through networks in ways the local networks are designed to prevent, or TLS termination.  Everything is live and ready to go.  (Time savings)
2. Xmidt uses WRP packets that are msgpack encoded - this is significantly faster and smaller than JSON or XML.  It is more suited to our needs than protobufs as well.  This savings is reflected in reduced decode time, code complexity and compute resources needed.  (Time savings, resource savings)
3. Xmidt is designed to be horizontally scalable  upon many different performance dimensions.  Number of concurrent connected CPEs, number of events flowing out of the system, number of API calls to GET or SET parameters are all independently adjustable.  This allows easy scaling to almost any needs.  No longer do you need to be limited by a single ACS or even a small cluster (if possible), instead you can have as many as you are willing to pay for (Time savings, cost control)
4. Xmidt's WRP protocol is designed to efficiently support binary and arbitrary messages.  This allows extensibility beyond what other protocols can do.  An example of this is [aker](https://github.com/xmidt-org/aker) which uses WRP CRUD messages to effectively communicate over the same TCP connection.  (Resource savings and good re-use)
5. Security is better because you don't need to leave a port open on a client - which is often running the oldest software in the ecosystem.  By closing down to incoming traffic & instead establishing a connection from the client to the cloud, fewer weaknesses are exposed against the CPE & the CPE can hostname validate the TLS 1.2+ connection.  Additional security measures can easily be added as desired.  (Security improvement)

Hopefully this is helpful.

**Comment by HapuHXY** [comment]
Wow, I get it! The explanation is very detailed. Thank you~~~
